//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization.Xliff.OM.Properties {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Localization.Xliff.OM.Standard.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ArgValidator_ElementReused_Format {
            get {
                return ResourceManager.GetString("ArgValidator_ElementReused_Format", resourceCulture);
            }
        }
        
        internal static string ArgValidator_InvalidId_Format {
            get {
                return ResourceManager.GetString("ArgValidator_InvalidId_Format", resourceCulture);
            }
        }
        
        internal static string ArgValidator_InvalidTypeOfMany_Format {
            get {
                return ResourceManager.GetString("ArgValidator_InvalidTypeOfMany_Format", resourceCulture);
            }
        }
        
        internal static string ArgValidator_InvalidType_Format {
            get {
                return ResourceManager.GetString("ArgValidator_InvalidType_Format", resourceCulture);
            }
        }
        
        internal static string ConverterBase_ValueNotImplemented_Format {
            get {
                return ResourceManager.GetString("ConverterBase_ValueNotImplemented_Format", resourceCulture);
            }
        }
        
        internal static string XliffElement_InvalidElement_Format {
            get {
                return ResourceManager.GetString("XliffElement_InvalidElement_Format", resourceCulture);
            }
        }
        
        internal static string StandardValidator_CodeBaseTypeNotSpecified {
            get {
                return ResourceManager.GetString("StandardValidator_CodeBaseTypeNotSpecified", resourceCulture);
            }
        }
        
        internal static string StandardValidator_DocumentTargetLanguageNotSpecified {
            get {
                return ResourceManager.GetString("StandardValidator_DocumentTargetLanguageNotSpecified", resourceCulture);
            }
        }
        
        internal static string StandardValidator_DocumentVersionNotSpecified {
            get {
                return ResourceManager.GetString("StandardValidator_DocumentVersionNotSpecified", resourceCulture);
            }
        }
        
        internal static string StandardValidator_DuplicateId_Format {
            get {
                return ResourceManager.GetString("StandardValidator_DuplicateId_Format", resourceCulture);
            }
        }
        
        internal static string StandardValidator_DuplicateOrder_Format {
            get {
                return ResourceManager.GetString("StandardValidator_DuplicateOrder_Format", resourceCulture);
            }
        }
        
        internal static string StandardValidator_DuplicateReference_Format {
            get {
                return ResourceManager.GetString("StandardValidator_DuplicateReference_Format", resourceCulture);
            }
        }
        
        internal static string StandardValidator_ElementNotFound_Format {
            get {
                return ResourceManager.GetString("StandardValidator_ElementNotFound_Format", resourceCulture);
            }
        }
        
        internal static string StandardValidator_EmptyString_Format {
            get {
                return ResourceManager.GetString("StandardValidator_EmptyString_Format", resourceCulture);
            }
        }
        
        internal static string StandardValidator_HRefNotSpecified {
            get {
                return ResourceManager.GetString("StandardValidator_HRefNotSpecified", resourceCulture);
            }
        }
        
        internal static string StandardValidator_IdNotSpecified {
            get {
                return ResourceManager.GetString("StandardValidator_IdNotSpecified", resourceCulture);
            }
        }
        
        internal static string StandardValidator_InvalidDataReference_Format {
            get {
                return ResourceManager.GetString("StandardValidator_InvalidDataReference_Format", resourceCulture);
            }
        }
        
        internal static string StandardValidator_InvalidMarkedSpanType {
            get {
                return ResourceManager.GetString("StandardValidator_InvalidMarkedSpanType", resourceCulture);
            }
        }
        
        internal static string StandardValidator_InvalidOrder_Format {
            get {
                return ResourceManager.GetString("StandardValidator_InvalidOrder_Format", resourceCulture);
            }
        }
        
        internal static string StandardValidator_InvalidPrefix_Format {
            get {
                return ResourceManager.GetString("StandardValidator_InvalidPrefix_Format", resourceCulture);
            }
        }
        
        internal static string StandardValidator_InvalidPriority_Format {
            get {
                return ResourceManager.GetString("StandardValidator_InvalidPriority_Format", resourceCulture);
            }
        }
        
        internal static string StandardValidator_InvalidResourceStringContent_Format {
            get {
                return ResourceManager.GetString("StandardValidator_InvalidResourceStringContent_Format", resourceCulture);
            }
        }
        
        internal static string StandardValidator_InvalidXliffSubTypeValue {
            get {
                return ResourceManager.GetString("StandardValidator_InvalidXliffSubTypeValue", resourceCulture);
            }
        }
        
        internal static string StandardValidator_LanguageMismatch {
            get {
                return ResourceManager.GetString("StandardValidator_LanguageMismatch", resourceCulture);
            }
        }
        
        internal static string StandardValidator_LanguageNotSpecified {
            get {
                return ResourceManager.GetString("StandardValidator_LanguageNotSpecified", resourceCulture);
            }
        }
        
        internal static string StandardValidator_NoElements_Format {
            get {
                return ResourceManager.GetString("StandardValidator_NoElements_Format", resourceCulture);
            }
        }
        
        internal static string StandardValidator_NonPositiveIndex {
            get {
                return ResourceManager.GetString("StandardValidator_NonPositiveIndex", resourceCulture);
            }
        }
        
        internal static string StandardValidator_SourceNotSpecified {
            get {
                return ResourceManager.GetString("StandardValidator_SourceNotSpecified", resourceCulture);
            }
        }
        
        internal static string StandardValidator_TargetNotSpecified {
            get {
                return ResourceManager.GetString("StandardValidator_TargetNotSpecified", resourceCulture);
            }
        }
        
        internal static string StandardValidator_Space_Not_Preserve {
            get {
                return ResourceManager.GetString("StandardValidator_Space_Not_Preserve", resourceCulture);
            }
        }
        
        internal static string StandardValidator_PropertyNotSpecified_Format {
            get {
                return ResourceManager.GetString("StandardValidator_PropertyNotSpecified_Format", resourceCulture);
            }
        }
        
        internal static string StandardValidator_SubflowNotFound_Format {
            get {
                return ResourceManager.GetString("StandardValidator_SubflowNotFound_Format", resourceCulture);
            }
        }
        
        internal static string StandardValidator_UnhandledException {
            get {
                return ResourceManager.GetString("StandardValidator_UnhandledException", resourceCulture);
            }
        }
        
        internal static string StandardValidator_XliffSubTypeMismatchFormatting {
            get {
                return ResourceManager.GetString("StandardValidator_XliffSubTypeMismatchFormatting", resourceCulture);
            }
        }
        
        internal static string StandardValidator_XliffSubTypeMismatchUserInterface {
            get {
                return ResourceManager.GetString("StandardValidator_XliffSubTypeMismatchUserInterface", resourceCulture);
            }
        }
        
        internal static string StandardValidator_ValueNotInRange_Format {
            get {
                return ResourceManager.GetString("StandardValidator_ValueNotInRange_Format", resourceCulture);
            }
        }
        
        internal static string XliffElement_UnknownElement_Format {
            get {
                return ResourceManager.GetString("XliffElement_UnknownElement_Format", resourceCulture);
            }
        }
        
        internal static string XliffReader_InvalidAttributeName_Format {
            get {
                return ResourceManager.GetString("XliffReader_InvalidAttributeName_Format", resourceCulture);
            }
        }
        
        internal static string StandardValidator_NoMatchingSourceReference_Format {
            get {
                return ResourceManager.GetString("StandardValidator_NoMatchingSourceReference_Format", resourceCulture);
            }
        }
        
        internal static string Codec_ElementNotDescendant_Format {
            get {
                return ResourceManager.GetString("Codec_ElementNotDescendant_Format", resourceCulture);
            }
        }
        
        internal static string XliffWriter_CannotSerializeElement_Format {
            get {
                return ResourceManager.GetString("XliffWriter_CannotSerializeElement_Format", resourceCulture);
            }
        }
        
        internal static string Codec_ElementsNotDescendantOfSame_Format {
            get {
                return ResourceManager.GetString("Codec_ElementsNotDescendantOfSame_Format", resourceCulture);
            }
        }
        
        internal static string Codec_TextCannotForElementBeNull_Format {
            get {
                return ResourceManager.GetString("Codec_TextCannotForElementBeNull_Format", resourceCulture);
            }
        }
        
        internal static string XliffDocument_SetIdNotSupported {
            get {
                return ResourceManager.GetString("XliffDocument_SetIdNotSupported", resourceCulture);
            }
        }
        
        internal static string XliffWriter_ExtensionTypeNotSupported_Format {
            get {
                return ResourceManager.GetString("XliffWriter_ExtensionTypeNotSupported_Format", resourceCulture);
            }
        }
        
        internal static string XmlNameInfo_InvalidLocalName {
            get {
                return ResourceManager.GetString("XmlNameInfo_InvalidLocalName", resourceCulture);
            }
        }
        
        internal static string XliffReader_ExtensionAlreadyRegistered_Format {
            get {
                return ResourceManager.GetString("XliffReader_ExtensionAlreadyRegistered_Format", resourceCulture);
            }
        }
        
        internal static string XliffElement_AttributeAlreadyRegistered_Format {
            get {
                return ResourceManager.GetString("XliffElement_AttributeAlreadyRegistered_Format", resourceCulture);
            }
        }
        
        internal static string StandardValidator_PropertyNotNMTOKEN_Format {
            get {
                return ResourceManager.GetString("StandardValidator_PropertyNotNMTOKEN_Format", resourceCulture);
            }
        }
        
        internal static string StandardValidator_CopyOfNotFound_Format {
            get {
                return ResourceManager.GetString("StandardValidator_CopyOfNotFound_Format", resourceCulture);
            }
        }
        
        internal static string StandardValidator_InvalidCopyOfElement_Format {
            get {
                return ResourceManager.GetString("StandardValidator_InvalidCopyOfElement_Format", resourceCulture);
            }
        }
        
        internal static string Utilities_TargetMustHaveSource {
            get {
                return ResourceManager.GetString("Utilities_TargetMustHaveSource", resourceCulture);
            }
        }
        
        internal static string Data_SpaceRestriction {
            get {
                return ResourceManager.GetString("Data_SpaceRestriction", resourceCulture);
            }
        }
        
        internal static string StandardValidator_DuplicateIdWithinHierarchy_Format {
            get {
                return ResourceManager.GetString("StandardValidator_DuplicateIdWithinHierarchy_Format", resourceCulture);
            }
        }
        
        internal static string StandardValidator_GlossaryEntryMissingChildren {
            get {
                return ResourceManager.GetString("StandardValidator_GlossaryEntryMissingChildren", resourceCulture);
            }
        }
        
        internal static string XliffWriter_PrefixInUse_Format {
            get {
                return ResourceManager.GetString("XliffWriter_PrefixInUse_Format", resourceCulture);
            }
        }
        
        internal static string XmlWriter_InvalidXmlSpecifier_Format {
            get {
                return ResourceManager.GetString("XmlWriter_InvalidXmlSpecifier_Format", resourceCulture);
            }
        }
        
        internal static string CodePoint_InvalidCode {
            get {
                return ResourceManager.GetString("CodePoint_InvalidCode", resourceCulture);
            }
        }
        
        internal static string CodePoint_OutOfRange {
            get {
                return ResourceManager.GetString("CodePoint_OutOfRange", resourceCulture);
            }
        }
        
        internal static string ArgValidator_StringDoesNotStartWith_Format {
            get {
                return ResourceManager.GetString("ArgValidator_StringDoesNotStartWith_Format", resourceCulture);
            }
        }
        
        internal static string StandardValidator_InlineTagsDontMatch_Format {
            get {
                return ResourceManager.GetString("StandardValidator_InlineTagsDontMatch_Format", resourceCulture);
            }
        }
        
        internal static string Xml_ProcessingInstruction_InvalidName_Format {
            get {
                return ResourceManager.GetString("Xml_ProcessingInstruction_InvalidName_Format", resourceCulture);
            }
        }
        
        internal static string StandardValidator_CanDeleteFailure_Format {
            get {
                return ResourceManager.GetString("StandardValidator_CanDeleteFailure_Format", resourceCulture);
            }
        }
        
        internal static string StandardValidator_SequenceCannotBeginWithNo {
            get {
                return ResourceManager.GetString("StandardValidator_SequenceCannotBeginWithNo", resourceCulture);
            }
        }
        
        internal static string StandardValidator_CanCopyFailure_Format {
            get {
                return ResourceManager.GetString("StandardValidator_CanCopyFailure_Format", resourceCulture);
            }
        }
        
        internal static string StandardValidator_CanCopyOrDeleteInvalidForCanReorder {
            get {
                return ResourceManager.GetString("StandardValidator_CanCopyOrDeleteInvalidForCanReorder", resourceCulture);
            }
        }
        
        internal static string StandardValidator_SequenceNotFound_Format {
            get {
                return ResourceManager.GetString("StandardValidator_SequenceNotFound_Format", resourceCulture);
            }
        }
        
        internal static string StandardValidator_SequenceDoesntMatch_Format {
            get {
                return ResourceManager.GetString("StandardValidator_SequenceDoesntMatch_Format", resourceCulture);
            }
        }
        
        internal static string StandardValidator_SequenceEntry_Format {
            get {
                return ResourceManager.GetString("StandardValidator_SequenceEntry_Format", resourceCulture);
            }
        }
        
        internal static string StandardValidator_MarkedSpanReferenceAndValueSpecified {
            get {
                return ResourceManager.GetString("StandardValidator_MarkedSpanReferenceAndValueSpecified", resourceCulture);
            }
        }
        
        internal static string StandardValidator_InvalidMarkedSpanReference_Format {
            get {
                return ResourceManager.GetString("StandardValidator_InvalidMarkedSpanReference_Format", resourceCulture);
            }
        }
        
        internal static string StandardValidator_StartEndPropertyMismatch_Format {
            get {
                return ResourceManager.GetString("StandardValidator_StartEndPropertyMismatch_Format", resourceCulture);
            }
        }
        
        internal static string StandardValidator_StartTagOccursAfterEndTag_Format {
            get {
                return ResourceManager.GetString("StandardValidator_StartTagOccursAfterEndTag_Format", resourceCulture);
            }
        }
        
        internal static string XliffElement_ElementOutOfOrder_Format {
            get {
                return ResourceManager.GetString("XliffElement_ElementOutOfOrder_Format", resourceCulture);
            }
        }
        
        internal static string StandardValidator_SpanningCodeEndIslatedAndStartRef {
            get {
                return ResourceManager.GetString("StandardValidator_SpanningCodeEndIslatedAndStartRef", resourceCulture);
            }
        }
        
        internal static string StandardValidator_SpanningCodeEndNotIslatedOrStartRef {
            get {
                return ResourceManager.GetString("StandardValidator_SpanningCodeEndNotIslatedOrStartRef", resourceCulture);
            }
        }
        
        internal static string StandardValidator_SpanningCodeStartIslatedWithRef_Format {
            get {
                return ResourceManager.GetString("StandardValidator_SpanningCodeStartIslatedWithRef_Format", resourceCulture);
            }
        }
        
        internal static string XliffReader_INoteContainerMissingNote_Format {
            get {
                return ResourceManager.GetString("XliffReader_INoteContainerMissingNote_Format", resourceCulture);
            }
        }
        
        internal static string XliffReader_OriginalDataMissingData {
            get {
                return ResourceManager.GetString("XliffReader_OriginalDataMissingData", resourceCulture);
            }
        }
        
        internal static string XliffElement_ChildAlreadyExists_Format {
            get {
                return ResourceManager.GetString("XliffElement_ChildAlreadyExists_Format", resourceCulture);
            }
        }
        
        internal static string StandardValidator_SourceLanguageMismatch {
            get {
                return ResourceManager.GetString("StandardValidator_SourceLanguageMismatch", resourceCulture);
            }
        }
        
        internal static string StandardValidator_TargetLanguageMismatch {
            get {
                return ResourceManager.GetString("StandardValidator_TargetLanguageMismatch", resourceCulture);
            }
        }
        
        internal static string StandardValidator_SpanningCodeStartNotIslated {
            get {
                return ResourceManager.GetString("StandardValidator_SpanningCodeStartNotIslated", resourceCulture);
            }
        }
        
        internal static string StandardValidator_ExplicitDependencyMissing_Format {
            get {
                return ResourceManager.GetString("StandardValidator_ExplicitDependencyMissing_Format", resourceCulture);
            }
        }
        
        internal static string StandardValidator_LanguageInvalid_Format {
            get {
                return ResourceManager.GetString("StandardValidator_LanguageInvalid_Format", resourceCulture);
            }
        }
        
        internal static string StandardValidator_CodeBaseWithCopyOfAndDataRef_Format {
            get {
                return ResourceManager.GetString("StandardValidator_CodeBaseWithCopyOfAndDataRef_Format", resourceCulture);
            }
        }
        
        internal static string StandardValidator_DifferentSequenceHierarchy {
            get {
                return ResourceManager.GetString("StandardValidator_DifferentSequenceHierarchy", resourceCulture);
            }
        }
        
        internal static string StandardValidator_SequenceAncestorNotInHierarchy {
            get {
                return ResourceManager.GetString("StandardValidator_SequenceAncestorNotInHierarchy", resourceCulture);
            }
        }
        
        internal static string StandardValidator_DuplicateExtensionId_Format {
            get {
                return ResourceManager.GetString("StandardValidator_DuplicateExtensionId_Format", resourceCulture);
            }
        }
        
        internal static string SubFormatStyleConverter_BackslashInKey {
            get {
                return ResourceManager.GetString("SubFormatStyleConverter_BackslashInKey", resourceCulture);
            }
        }
        
        internal static string SubFormatStyleConverter_CommaInValue_Format {
            get {
                return ResourceManager.GetString("SubFormatStyleConverter_CommaInValue_Format", resourceCulture);
            }
        }
        
        internal static string SubFormatStyleConverter_InvalidKey_Format {
            get {
                return ResourceManager.GetString("SubFormatStyleConverter_InvalidKey_Format", resourceCulture);
            }
        }
        
        internal static string SubFormatStyleConverter_KeyWithoutValue_Format {
            get {
                return ResourceManager.GetString("SubFormatStyleConverter_KeyWithoutValue_Format", resourceCulture);
            }
        }
        
        internal static string XliffElement_PropertyNotSupported_Format {
            get {
                return ResourceManager.GetString("XliffElement_PropertyNotSupported_Format", resourceCulture);
            }
        }
        
        internal static string StandardValidator_FormatStyleSubFormatWithoutFormat {
            get {
                return ResourceManager.GetString("StandardValidator_FormatStyleSubFormatWithoutFormat", resourceCulture);
            }
        }
        
        internal static string StandardValidator_FormatStyleWithSpanEndNotIsolated {
            get {
                return ResourceManager.GetString("StandardValidator_FormatStyleWithSpanEndNotIsolated", resourceCulture);
            }
        }
        
        internal static string StandardValidator_HRefNotSpecifiedWhenEmpty_Format {
            get {
                return ResourceManager.GetString("StandardValidator_HRefNotSpecifiedWhenEmpty_Format", resourceCulture);
            }
        }
        
        internal static string StandardValidator_HRefNotSpecifiedWhenRequired {
            get {
                return ResourceManager.GetString("StandardValidator_HRefNotSpecifiedWhenRequired", resourceCulture);
            }
        }
        
        internal static string StandardValidator_MimeTypeRequired {
            get {
                return ResourceManager.GetString("StandardValidator_MimeTypeRequired", resourceCulture);
            }
        }
        
        internal static string StandardValidator_ResourceItemRefInvalidReference_Format {
            get {
                return ResourceManager.GetString("StandardValidator_ResourceItemRefInvalidReference_Format", resourceCulture);
            }
        }
        
        internal static string StandardValidator_RuleDefinitionInvalid {
            get {
                return ResourceManager.GetString("StandardValidator_RuleDefinitionInvalid", resourceCulture);
            }
        }
        
        internal static string StandardValidator_RuleExistsInSourceInvalid {
            get {
                return ResourceManager.GetString("StandardValidator_RuleExistsInSourceInvalid", resourceCulture);
            }
        }
        
        internal static string StandardValidator_ValueMustBeNOrGreater_Format {
            get {
                return ResourceManager.GetString("StandardValidator_ValueMustBeNOrGreater_Format", resourceCulture);
            }
        }
        
        internal static string StandardValidator_ProfileNotSpecified {
            get {
                return ResourceManager.GetString("StandardValidator_ProfileNotSpecified", resourceCulture);
            }
        }
        
        internal static string StandardValidator_SameSizeInfoAndSizeInfoReferencePresence {
            get {
                return ResourceManager.GetString("StandardValidator_SameSizeInfoAndSizeInfoReferencePresence", resourceCulture);
            }
        }
        
        internal static string StandardValidator_SizeRestrictionAttributeWithSpanEndNotIsolated_Format {
            get {
                return ResourceManager.GetString("StandardValidator_SizeRestrictionAttributeWithSpanEndNotIsolated_Format", resourceCulture);
            }
        }
        
        internal static string StandardValidator_InvalidMarkedSpanReferenceSelectorPath_Format {
            get {
                return ResourceManager.GetString("StandardValidator_InvalidMarkedSpanReferenceSelectorPath_Format", resourceCulture);
            }
        }
        
        internal static string StandardValidator_StartEndCanReorderMismatch {
            get {
                return ResourceManager.GetString("StandardValidator_StartEndCanReorderMismatch", resourceCulture);
            }
        }
        
        internal static string StandardValidator_ItemPropertyNull {
            get {
                return ResourceManager.GetString("StandardValidator_ItemPropertyNull", resourceCulture);
            }
        }
        
        internal static string StandardValidator_ResourceDataMissingItems {
            get {
                return ResourceManager.GetString("StandardValidator_ResourceDataMissingItems", resourceCulture);
            }
        }
        
        internal static string StandardValidator_ResourceItemMissingChildren {
            get {
                return ResourceManager.GetString("StandardValidator_ResourceItemMissingChildren", resourceCulture);
            }
        }
        
        internal static string StandardValidator_ResourceItemSourceMissingWithNoContext {
            get {
                return ResourceManager.GetString("StandardValidator_ResourceItemSourceMissingWithNoContext", resourceCulture);
            }
        }
        
        internal static string XliffElement_InnerTextNotSupported_Format {
            get {
                return ResourceManager.GetString("XliffElement_InnerTextNotSupported_Format", resourceCulture);
            }
        }
        
        internal static string StandardValidator_SpanningCodeEndStartRefAndId {
            get {
                return ResourceManager.GetString("StandardValidator_SpanningCodeEndStartRefAndId", resourceCulture);
            }
        }
        
        internal static string StandardValidator_OutputResolverFailed_Format {
            get {
                return ResourceManager.GetString("StandardValidator_OutputResolverFailed_Format", resourceCulture);
            }
        }
    }
}
